### PR TITLE
fix multi chunks, replace expose-loader

### LINKED ISSUE #5966: peer dependency errors around nested files
We are sometimes getting error around peer dependencies an internal files coming from the env template.
This is especially problematic in our `community-react` env.

symptoms:

* sometimes deps are missing (like graphql/language). This will cause an "cannot read *** of undefined" error. Can be solved with a custom alias.
* sometimes getting the "require() is not defined" error. I am thinking this might be code injected by the expose-loader that should have been transpiled by webpack

what I know so far:

* When tagging an env, bit is generating an "env template" that includes the peer dependencies, to reuse them and conserve size.
* The env template adds the peer deps to the window using the [expose-loader](https://webpack.js.org/loaders/exports-loader/), and enforces it using webpack [alias](https://webpack.js.org/configuration/resolve/#resolvealias) option.
* Consuming components access the exposed peers using webpack's [externals](https://webpack.js.org/configuration/externals/) option.
  * this doesn't handle internal files, like `graphql/language` or `react-dom/server`
  * also loading the package from cjs or esm could load different files (like "./main.cjs" and "./index.mjs")

what we've done so far:

* list all the internal files used (by searching in the workspace and node_modules), and add a custom alias for them
* update the `test` of the expose-loader to load the same file as the alias

things we should try:

* [x] find an alternative for expose-loader. it might be better to load peers as umd, instead of loading them into window webpack's externals already supports umd, systemjs, jsonp, etc
  > some alternative exists, but may not be relevant: [module-federation](https://webpack.js.org/concepts/module-federation/) (which is very opinionated, and might lead us to a worse path), and webpack's [DLL plugin](https://webpack.js.org/plugins/dll-plugin/)
* [ ] fork `expose-loader` to output umd (or others) instead of writing directly to window, and maybe automatically calculate the package name based on the requested resource (ie `graphql/langauge` -> `Graphql__language`). Externals already supports many formats (like umd, window, system) and might allow us to tackle nested files.
* [ ] fix `community-react`'s missing `"type": "module"`. Without it, the components are treated de-factor as cjs and might load incorrect dependencies.
* [ ] somehow force webpack to load the esm / cjs version of the package instead of determining it automatically itself

blockers:

- [ ] we don't have a solution for peer nested files (ie. `graphql/language`)
- [ ] need to ensure mixing cjs/esm works properly (ie. `import { Link } from 'react-router-dom'` and `require('react-router-dom').Link` will lead to different files

### PR DESCRIPTION
**Pull request by KutnerUri**
## Proposed Changes

- replace expose-loader completely with a custom link file.
- gather template specific configs in their own file
- fix clashing webpack definitions with the `chunkLoadingGlobal` option
- fix preview chunks loading order

resolves #5966

## TODO:
- [x] fix error `Self-reference dependency has unused export name` from package `react-native`, because of optimizations
- [x] fix race condition when loading previews
- [x] verify code works without local changes
- [x] local errors

✅ READY TO MERGE

### CODE REVIEW

File: scopes/preview/preview/strategies/generate-component-link.ts [hunk 1]
```diff
@@ -17,15 +17,15 @@ export function generateComponentLink(modules: ModuleVar[]): string {
   // import per preview file
   const importStr: string = links
     .map(({ entries }) => entries.map(({ path, linkName }) => `import * as ${linkName} from '${path}'`).join(';\n'))
-    .join('\n');
+    .join(';\n');
```
Comment (KutnerUri) [inline scopes/preview/preview/strategies/generate-component-link.ts:20]: just cleanup - added missing `;`

**Review by GiladShoham — APPROVED** [review]
