### PR TITLE
provide context path to tester

### LINKED ISSUE #1154: context isn't passed to getDynamicPackageDependencies while using tester
## Expected Behavior
context should have componentDir and workspaceDir while calling `getDynamicPackageDependencies`

## Actual Behavior
context is undefined 

## Steps to Reproduce the Problem

  1. Implement an example tester which has the function getDynamicPackageDependencies
  2. console.log(context) --> context is undefined
  
## Specifications

  - Bit version: 13.0.3 (should be applicable to 13.0.4) 
  - Node version: 10.6.0 
  - npm / yarn version: 6.2.0
  - Platform: mac os high sierra 
  - Bit compiler (include version): n/a
  - Bit tester (include version): any

I'm currently working on a PR to fix this issue.

### PR DESCRIPTION
**Pull request by qballer**
## Proposed Changes

  - add context path to getDynamicPackageDependencies 
  - add context path to action from consumer.runSpecs
  - fixes #1154

---
This change is [Reviewable](https://reviewable.io/reviews/teambit/bit/1155)

### CODE REVIEW

File: src/consumer/component/consumer-component.js [hunk 1]
```diff
@@ -712,13 +712,24 @@ export default class Component {
 
       let specsResults: RawTestsResults[];
 
+      let contextPaths;
+      if (this.tester && this.tester.context) {
+        contextPaths = this.tester.context;
+      } else if (consumer && consumer.bitMap) {
+        contextPaths = {
+          componentDir: consumer.bitMap.projectRoot
```
Comment (GiladShoham) [inline src/consumer/component/consumer-component.js]: I'm not sure this is what you expect to get.
The project root is not the component dir but the workspace dir.
you probably want to use:
this.componentMap.getTrackDir
